print('Please enter the following:')
adjective = input('\nadjective: ')
animal = input('animal: ')
verb_1 = input('verb: ')
exclamation = input('exclamation: ')
verb_2= input('verb: ')
verb_3 = input('verb: ')
verb_4 = input('verb: ')
noun_2 = input('noun: ')
noun_3 = input('noun: ')
noun_4 = input('noun: ')
print('\nYour story is:\n')
print(f'The other day, I was really in trouble. It all started when I saw a very {adjective} {animal} {verb_1} down the hallway. "{exclamation.capitalize()}!" I yelled. But all I could think to do was to {verb_2} over and over. Miraculously, that caused it to stop, but not before it tried to {verb_3} right in front of my famiy. Then the {animal} started {verb_4}ing right at me! I grabbed my {noun_2} and pulled the {noun_3}. It exploded into a flaming ball of {noun_4}.')