age = int(input('\nHow old are you? '))
next_birthday = (age + 1)
print(f'On your next birthday, you will be {next_birthday}\n')
eggs = int(input('How many egg cartons do you have? '))
total_eggs = (eggs*12)
print(f'You have {total_eggs} eggs\n')
cookies = int(input('How many cookies do you have? '))
people = int(input('How many people are there? '))
print(f'Each person may have {cookies/people} cookies\n')
